name: Anti-Inactivity Keepalive

on:
  schedule:
    - cron: "17 1 1 * *" # Evita la franja de alta demanda del minuto 00

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Empty Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "chore: keepalive $(date +'%B %Y')"
          git push
